# Specify development configuration.

# specify-cli dependency
cli = { git = "https://github.com/augentic/specify-cli", branch = "rfc-41" }
# cli = { version = "0.2.0" }
# optionally, use Specify.local.toml so a local path is not committed
# cli = { path = "../specify-cli" }
