//! Compiles the mock adapter example (`examples/adapter`) to a
//! `wasm32-wasip2` component and generates `gen.rs` with its artifact path.
//!
//! Patterned on omnia's `crates/test-utils/build.rs`: a nested cargo build
//! into a dedicated target directory under `OUT_DIR`, then the artifact's
//! dep-info registered as `rerun-if-changed` so an SDK edit rebuilds the
//! fixture.

// `crates/clippy.toml` is the guest deny-list; a build script is host code
// whose one job is spawning the nested cargo build.
#![expect(
    clippy::disallowed_types,
    reason = "a build script must spawn cargo for the wasm32 fixture build"
)]

use std::collections::HashSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::{env, fs};

const WASM_TARGET: &str = "wasm32-wasip2";

/// `[[example]]` names in the root package built as fixture components.
const EXAMPLES: [&str; 1] = ["adapter"];

fn main() {
    // A wasm32 build of this crate is empty; never nest a build from one.
    if env::var("CARGO_CFG_TARGET_ARCH").as_deref() == Ok("wasm32") {
        write_gen("");
        return;
    }

    let manifest_dir =
        PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set"));
    let root = manifest_dir.join("../..").canonicalize().expect("workspace root");
    for tracked in ["examples/adapter", "crates/adapter", "wit", "Cargo.lock"] {
        println!("cargo:rerun-if-changed={}", root.join(tracked).display());
    }

    let target_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("fixtures");
    build_examples(&root, &target_dir);

    // Always `debug`: the nested build uses the dev profile regardless of
    // the outer profile.
    let examples = target_dir.join(WASM_TARGET).join("debug/examples");
    let mut generated = String::from("// Generated by crates/test-utils/build.rs.\n");
    let mut seen = HashSet::new();
    for name in EXAMPLES {
        let artifact = examples.join(format!("{name}.wasm"));
        assert!(artifact.exists(), "no artifact for example `{name}` at {}", artifact.display());
        let constant = format!("MOCK_{}", name.to_uppercase());
        let path = artifact.to_str().expect("artifact path is UTF-8");
        writeln!(
            generated,
            "/// Path to the compiled `{name}` example component.\npub const {constant}: &str = \
             {path:?};"
        )
        .expect("writing to a String");
        emit_dep_info(&artifact, &mut seen);
    }
    write_gen(&generated);
}

fn write_gen(contents: &str) {
    let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("gen.rs");
    fs::write(&out, contents).unwrap_or_else(|err| panic!("writing {}: {err}", out.display()));
}

fn build_examples(root: &Path, target_dir: &Path) {
    // Reuse Cargo from the parent build to stay on its toolchain.
    let cargo = env::var_os("CARGO").expect("CARGO is set");
    let mut child = Command::new(cargo);
    child.current_dir(root).args(["build", "--locked", "--target", WASM_TARGET]);
    for name in EXAMPLES {
        child.args(["--example", name]);
    }
    let deny_warnings = rustflags_deny_warnings();
    sanitize(&mut child);
    child.env("CARGO_TARGET_DIR", target_dir);
    if deny_warnings {
        child.env("RUSTFLAGS", "-Dwarnings");
    }

    let status = child.status().unwrap_or_else(|err| {
        panic!("failed to spawn the {WASM_TARGET} fixture build: {err}");
    });
    assert!(
        status.success(),
        "the fixture components could not be built; install the target with `rustup target add \
         {WASM_TARGET}` and retry"
    );
}

// Propagate only warning denial to the nested build; other outer flags are
// native-target concerns that don't apply to the wasm32 guests.
fn rustflags_deny_warnings() -> bool {
    env::var("RUSTFLAGS")
        .is_ok_and(|flags| flags.contains("-Dwarnings") || flags.contains("-D warnings"))
}

// Prevent host flags from leaking into wasm; preserve Cargo settings and the
// inherited toolchain to avoid mixed-compiler E0514 failures. When the outer
// command is `cargo clippy`, the workspace wrapper would run clippy-driver
// over the guests' wasm32 dep tree; the fixtures are a plain rustc build.
fn sanitize(child: &mut Command) {
    for (key, _) in env::vars_os() {
        let Some(key) = key.to_str() else { continue };
        let kept = key == "CARGO_HOME" || key == "CARGO_NET_OFFLINE";
        if key.starts_with("CARGO_") && !kept {
            child.env_remove(key);
        }
    }
    for key in ["RUSTFLAGS", "RUSTDOCFLAGS", "RUSTC", "RUSTC_WRAPPER", "RUSTC_WORKSPACE_WRAPPER"] {
        child.env_remove(key);
    }
}

// Cargo's extra dep-info sits next to the uplifted example (`{name}.d`). It
// lists the example's sources plus every local path dependency (the adapter
// SDK, the engine, ...), so edits there rebuild the fixture.
fn emit_dep_info(artifact: &Path, seen: &mut HashSet<String>) {
    let dep_info = artifact.with_extension("d");
    let contents = fs::read_to_string(&dep_info)
        .unwrap_or_else(|err| panic!("reading {} ({err})", dep_info.display()));
    for line in contents.lines() {
        let Some((_, deps)) = line.split_once(": ") else {
            continue;
        };
        // dep-info escapes spaces in paths as `\ `.
        let mut current = String::new();
        for part in deps.split(' ') {
            if let Some(prefix) = part.strip_suffix('\\') {
                current.push_str(prefix);
                current.push(' ');
            } else if !part.is_empty() {
                current.push_str(part);
                if seen.insert(current.clone()) {
                    println!("cargo:rerun-if-changed={current}");
                }
                current.clear();
            }
        }
    }
}
