#!/usr/bin/env bash
# Rebuild the WASI fixture components under
# `tests/fixtures/tools-test-project/wasm/` (consumed by the
# `specify lint project` declared-tool path test in `tests/lint.rs`).
#
# These fixtures change rarely; the `.wasm` outputs are checked in.
# Run this script whenever a fixture's Rust source changes, then
# commit the regenerated bytes.
#
# Requirements:
#   - `wasm32-wasip2` target installed (`rustup target add wasm32-wasip2`)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

CARGO_TARGET_DIR=target/tools-test-fixtures cargo build \
    --manifest-path tests/fixtures/tools-test-project/src-rust/Cargo.toml \
    --target wasm32-wasip2 \
    --release \
    --bins

mkdir -p tests/fixtures/tools-test-project/wasm

for bin in echo read-only read-write read-denied; do
    cp "target/tools-test-fixtures/wasm32-wasip2/release/${bin}.wasm" \
        "tests/fixtures/tools-test-project/wasm/${bin}.wasm"
done
