//! deployment-manifest generation.
//!
//! After hydration, the provisioning surface generates the deployment
//! manifest the composed runtime reads: one `[[guest]]` per resolved
//! adapter component ([`DeployGuest`] — pinned store entries and
//! project-local bare-name components alike), the core/workflow guest
//! with its adapter-contract link allow-list, the project directory as
//! the writable `"."` mount, and one `/mcp/<name>` HTTP route per
//! adapter. The manifest is a derived artifact in the per-project
//! cache (`<project-cache>/deployment/omnia.toml`): regenerated by
//! `specify init`, `specify adapters sync`, and the guest leg on every
//! drive; never committed, never hand-edited.
//!
//! The store is load-bearing at runtime: [`generate`] verifies every
//! referenced component exists before writing, so a dangling pinned
//! entry is the typed `adapter-not-installed` (naming the identity and
//! the literal sync command), never a generated-then-broken manifest.
//!
//! The core guest arrives as a plain `core` path parameter (core
//! versioned by the binary): the binary resolves it by its own version — a development
//! override, else the hydrated `specify:core@<binary version>` store
//! entry — so this generator never knows how the core was obtained.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use specify_error::Error;
use specify_model::atomic::bytes_write;
use specify_schema::cache::project_cache_dir;

use crate::adapter::Axis;

/// Generated manifest filename inside the deployment tenant — the same
/// name the project-root developer override uses.
const MANIFEST_FILENAME: &str = "omnia.toml";

/// One adapter guest in the deployment set.
///
/// The generator covers the whole deployment, not just the hydrated
/// pins: a pinned identity (`version: Some`) points at its immutable
/// global-store entry, while a bare development name (`version: None`)
/// points at its project-local component (the component cache or the
/// sibling release build) — that resolution order holds
/// unchanged.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeployGuest {
    /// Adapter axis — the `<axis>:` half of the deployment guest id.
    pub axis: Axis,
    /// Kebab-case adapter name (the `/mcp/<name>` route).
    pub name: String,
    /// Exact semver pin when the component is a global-store entry;
    /// `None` for a project-local bare-name component.
    pub version: Option<semver::Version>,
    /// Absolute path to the resolved component file.
    pub component: PathBuf,
}

/// The per-project deployment tenant —
/// `<project-cache>/deployment/`.
#[must_use]
pub fn deployment_dir(project_dir: &Path) -> PathBuf {
    project_cache_dir(project_dir).join("deployment")
}

/// Absolute path of the generated deployment manifest —
/// `<project-cache>/deployment/omnia.toml`.
#[must_use]
pub fn manifest_path(project_dir: &Path) -> PathBuf {
    deployment_dir(project_dir).join(MANIFEST_FILENAME)
}

/// The typed store-miss error for a pinned identity the deployment
/// needs.
///
/// Names the identity, the probed entry, and the literal sync command
/// ([`Error::Validation`], exit 2). Shared by the generator's presence
/// gate and the deployment-assembly probes in the binary.
#[must_use]
pub fn adapter_not_installed(name: &str, version: &semver::Version, entry: &Path) -> Error {
    Error::validation_failed(
        "adapter-not-installed",
        "every pinned adapter in the deployment must be installed in the global store",
        format!(
            "adapter `{name}@{version}` is not installed in the global store at {}; the runtime \
             never fetches — run `specify adapters sync` to hydrate the declared set",
            entry.display()
        ),
    )
}

/// Generate the deployment manifest and return its path.
///
/// `project_dir` must be absolute — it becomes the writable `"."`
/// mount. The document is assembled from the core guest at `core`
/// plus the resolved adapter set and atomically written at
/// [`manifest_path`].
///
/// # Errors
///
/// - `adapter-not-installed` ([`Error::Validation`], exit 2) — a
///   pinned adapter's store entry is dangling (the store is
///   load-bearing; a broken manifest is never written).
/// - `adapter-not-found` — a project-local component path is dangling.
/// - [`Error::Io`] — the atomic write failed.
pub fn generate(
    project_dir: &Path, core: &Path, adapters: &[DeployGuest],
) -> Result<PathBuf, Error> {
    for adapter in adapters {
        if adapter.component.is_file() {
            continue;
        }
        return Err(dangling_component(adapter));
    }
    // The manifest mounts the store root read-only; a not-yet-hydrated
    // machine has no store directory, so materialise the (empty) root
    // rather than hand Omnia a dangling preopen path.
    std::fs::create_dir_all(specify_schema::cache::adapter_store_root()).map_err(Error::Io)?;
    let path = manifest_path(project_dir);
    bytes_write(&path, document(core, project_dir, adapters).as_bytes())?;
    Ok(path)
}

/// The typed presence-gate error for a dangling component: the pinned
/// form is [`adapter_not_installed`]; a project-local bare name is
/// `adapter-not-found` with the rebuild remedy.
fn dangling_component(adapter: &DeployGuest) -> Error {
    adapter.version.as_ref().map_or_else(
        || Error::Diag {
            code: "adapter-not-found",
            detail: format!(
                "adapter `{}` has no component at {}; rebuild it with `cargo make release` in \
                 the adapters repo or pin a published version",
                adapter.name,
                adapter.component.display()
            ),
        },
        |version| adapter_not_installed(&adapter.name, version, &adapter.component),
    )
}

/// Render the deployment manifest document: the core guest with the
/// adapter-contract link allow-list, one `[[guest]]` + `[[route.http]]`
/// per adapter, the writable `"."` mount, the per-project derived
/// cache mounted at [`specify_schema::cache::GUEST_CACHE_MOUNT`]
/// (guest routing: the guest's `rules export` reads the codex tenant
/// and init's scaffold leg writes the component and codex tenants),
/// the global adapter store mounted **read-only** at
/// [`specify_schema::cache::GUEST_STORE_MOUNT`] (forwarded verbs
/// resolve pinned identities in-guest; hydration stays native), and
/// the in-process transport default — the same shape the in-tree
/// developer manifest models.
fn document(core: &Path, mount: &Path, adapters: &[DeployGuest]) -> String {
    let mut doc = format!(
        "[[guest]]\n\
         id = \"workflow\"\n\
         source.path = {core}\n\
         link = [\"specify:adapter/source@0.1.0\", \"specify:adapter/target@0.1.0\"]\n\n",
        core = toml_string(core),
    );
    for adapter in adapters {
        let _ = writeln!(
            doc,
            "[[guest]]\nid = \"{id}\"\nsource.path = {wasm}\n",
            id = guest_id(adapter),
            wasm = toml_string(&adapter.component),
        );
    }
    let _ =
        writeln!(doc, "[[mount]]\nname = \".\"\npath = {}\nwritable = true\n", toml_string(mount));
    let _ = writeln!(
        doc,
        "[[mount]]\nname = \"{name}\"\npath = {path}\nwritable = true\n",
        name = specify_schema::cache::GUEST_CACHE_MOUNT,
        path = toml_string(&project_cache_dir(mount)),
    );
    let _ = writeln!(
        doc,
        "[[mount]]\nname = \"{name}\"\npath = {path}\nwritable = false\n",
        name = specify_schema::cache::GUEST_STORE_MOUNT,
        path = toml_string(&specify_schema::cache::adapter_store_root()),
    );
    for adapter in adapters {
        let _ = writeln!(
            doc,
            "[[route.http]]\nprefix = \"/mcp/{name}\"\nguest = \"{id}\"\n",
            name = adapter.name,
            id = guest_id(adapter),
        );
    }
    doc.push_str("[transport]\ndefault = \"in-process\"\n");
    doc
}

/// Deployment guest id — `<axis>:<name>`.
fn guest_id(adapter: &DeployGuest) -> String {
    format!("{}:{}", adapter.axis, adapter.name)
}

/// A host path as a TOML basic string: quoted, with `\`, `"`, and the
/// control characters TOML forbids in basic strings (U+0000–U+001F,
/// U+007F) escaped, so Windows separators, quote characters, or
/// control characters in host paths cannot break the manifest parse.
fn toml_string(path: &Path) -> String {
    let mut escaped = String::from("\"");
    for ch in path.display().to_string().chars() {
        match ch {
            '\\' => escaped.push_str("\\\\"),
            '"' => escaped.push_str("\\\""),
            '\n' => escaped.push_str("\\n"),
            '\t' => escaped.push_str("\\t"),
            '\r' => escaped.push_str("\\r"),
            c if c.is_control() && c.is_ascii() => {
                let _ = write!(escaped, "\\u{:04X}", c as u32);
            }
            c => escaped.push(c),
        }
    }
    escaped.push('"');
    escaped
}
