
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.cc]]
version = "1.2.56"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.44"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.iana-time-zone]]
version = "0.1.65"
criteria = "safe-to-deploy"

[[exemptions.itoa]]
version = "1.0.17"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.91"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.29"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.serde_yaml]]
version = "0.9.34+deprecated"
criteria = "safe-to-deploy"

[[exemptions.toml]]
version = "0.9.12+spec-1.1.0"
criteria = "safe-to-deploy"

[[exemptions.tracing]]
version = "0.1.44"
criteria = "safe-to-deploy"

[[exemptions.tracing-attributes]]
version = "0.1.31"
criteria = "safe-to-deploy"

[[exemptions.tracing-core]]
version = "0.1.36"
criteria = "safe-to-deploy"

[[exemptions.tracing-subscriber]]
version = "0.3.22"
criteria = "safe-to-deploy"

[[exemptions.unsafe-libyaml]]
version = "0.2.11"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.114"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.114"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.114"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.114"
criteria = "safe-to-deploy"
