[package]
name = "mock"
description = "SDK-native mock adapter"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
adapter.workspace = true
omnia-guest.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
linked.workspace = true
omnia-testkit.workspace = true
project.workspace = true
serde_json.workspace = true
tempfile.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
