pub mod openspec;

use std::path::{Path, PathBuf};

use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::pipeline::RepoGroup;
use crate::registry::Registry;

/// Interface between the orchestrator and the spec engine.
/// All tool-specific logic (OpenSpec, Spec Kit, etc.) lives behind this trait.
pub trait SpecEngine {
    /// Initialize the spec engine in a target repo (if not already present).
    fn init(&self, repo_dir: &Path) -> Result<()>;

    /// Install schema and templates into the target repo.
    fn install_schema(&self, repo_dir: &Path, schema_source: &Path) -> Result<()>;

    /// Create a new change scaffold from a brief.
    fn create_change(&self, repo_dir: &Path, brief: &ChangeBrief) -> Result<()>;

    /// Return the directory where change artifacts live in the target repo.
    fn change_dir(&self, repo_dir: &Path, change_name: &str) -> PathBuf;

    /// Generate the agent command to apply (implement) the change.
    fn agent_apply_command(&self, change_name: &str) -> String;

    /// Generate the agent command to archive the change.
    fn agent_archive_command(&self, change_name: &str) -> String;

    /// Generate a merged config for the target repo.
    fn generate_config(
        &self, base_config: &Path, registry: &Registry, group: &RepoGroup,
    ) -> Result<String>;
}

/// Per-repo artifact generated by `opsx fan-out`. The spec engine adapter reads
/// this to scaffold the change in the target repo.
#[derive(Debug, Serialize, Deserialize)]
pub struct ChangeBrief {
    pub change: BriefChange,
    pub target: BriefTarget,
    pub specs: BriefSpecs,
    pub upstream: BriefUpstream,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BriefChange {
    pub name: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BriefTarget {
    pub repo: String,
    pub crates: Vec<String>,
    pub domain: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BriefSpecs {
    pub files: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct BriefUpstream {
    pub architecture: String,
    pub contracts: String,
    pub pipeline: String,
}
