use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};
use serde_yml::Value;

use super::{ChangeBrief, SpecEngine};
use crate::git;
use crate::pipeline::RepoGroup;
use crate::registry::Registry;

pub struct OpenSpecEngine;

impl SpecEngine for OpenSpecEngine {
    fn init(&self, repo_dir: &Path) -> Result<()> {
        if repo_dir.join("openspec").exists() {
            tracing::debug!("openspec/ already exists, skipping init");
            return Ok(());
        }
        git::run_cmd("openspec", &["init"], repo_dir).context("openspec init")?;
        Ok(())
    }

    fn install_schema(&self, repo_dir: &Path, schema_source: &Path) -> Result<()> {
        let dest = repo_dir.join("openspec/schemas/augentic");
        std::fs::create_dir_all(&dest).context("creating schema dir")?;

        let src_schema = schema_source.join("schemas/schema.yaml");
        if src_schema.exists() {
            std::fs::copy(&src_schema, dest.join("schema.yaml")).context("copying schema.yaml")?;
        }

        let src_templates = schema_source.join("templates");
        if src_templates.exists() {
            let templates_dest = dest.join("templates");
            std::fs::create_dir_all(&templates_dest)?;
            for entry in std::fs::read_dir(&src_templates)? {
                let entry = entry?;
                let path = entry.path();
                if path.is_file() {
                    std::fs::copy(&path, templates_dest.join(entry.file_name()))?;
                }
            }
        }

        Ok(())
    }

    fn create_change(&self, repo_dir: &Path, brief: &ChangeBrief) -> Result<()> {
        git::run_cmd(
            "openspec",
            &["new", "change", &brief.change.name, "--schema", "augentic"],
            repo_dir,
        )
        .context("openspec new change")?;
        Ok(())
    }

    fn change_dir(&self, repo_dir: &Path, change_name: &str) -> PathBuf {
        repo_dir.join("openspec/changes").join(change_name)
    }

    fn agent_apply_command(&self, change_name: &str) -> String {
        format!("/opsx:apply {change_name}")
    }

    fn agent_archive_command(&self, change_name: &str) -> String {
        format!("/opsx:archive {change_name}")
    }

    fn generate_config(
        &self, base_config: &Path, _registry: &Registry, group: &RepoGroup,
    ) -> Result<String> {
        let base = std::fs::read_to_string(base_config)
            .with_context(|| format!("reading base config {}", base_config.display()))?;
        let mut yaml: Value = serde_yml::from_str(&base).context("parsing base config as YAML")?;

        let target_ctx = format!(
            concat!(
                "# --- Target context (auto-generated by opsx) ---\n",
                "Repo: {}\n",
                "Crates: {}\n",
                "Domain: {}\n",
                "Project dir: {}\n",
            ),
            group.repo,
            group.crates.join(", "),
            group.domain,
            group.project_dir,
        );
        let root = yaml.as_mapping_mut().context("base config must be a YAML object at root")?;
        let context_key = Value::String(String::from("context"));
        let existing =
            root.get_mut(&context_key).context("base config missing required 'context' key")?;
        let Value::String(current_context) = existing else {
            bail!("base config 'context' must be a string block");
        };
        if !current_context.ends_with('\n') {
            current_context.push('\n');
        }
        current_context.push('\n');
        current_context.push_str(&target_ctx);

        serde_yml::to_string(&yaml).context("serializing merged config")
    }
}
