//! Write planner that decides whether to create, replace, or leave
//! `AGENTS.md` alone, splicing the renderer's generated bytes into any
//! operator-authored prefix and suffix that [`super::parse`] surfaced.

use super::parse::{FenceError, parse_document};

/// Kind of write the planner selected.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteDisposition {
    /// `AGENTS.md` was absent, so the full generated document should be created.
    Create,
    /// `AGENTS.md` was unfenced and `--force` allowed a full rewrite.
    ForceRewriteUnfenced,
    /// `AGENTS.md` was fenced, so only the generated block should be replaced.
    ReplaceFencedBlock,
    /// The planned output is byte-identical to the existing `AGENTS.md`.
    Unchanged,
}

/// Pure write-plan result for `AGENTS.md`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PlannedWrite {
    /// Complete bytes that should be persisted to `AGENTS.md`.
    pub bytes: Vec<u8>,
    /// Policy decision used to produce `bytes`.
    pub disposition: WriteDisposition,
}

/// Compose final `AGENTS.md` bytes according to the context fence policy.
///
/// # Errors
///
/// [`FenceError::GeneratedDocumentMissingFences`] when the generated
/// document carries no fences,
/// [`FenceError::ExistingUnfencedAgentsMd`] when the existing file is
/// unfenced and `force` is off, and the [`parse_document`] errors for
/// malformed fences on either side.
pub fn plan_agents_write(
    existing: Option<&[u8]>, generated_document: &[u8], force: bool,
) -> Result<PlannedWrite, FenceError> {
    let generated =
        parse_document(generated_document)?.ok_or(FenceError::GeneratedDocumentMissingFences)?;

    let Some(existing) = existing else {
        return Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::Create,
        });
    };

    match parse_document(existing)? {
        Some(current) => {
            let mut bytes = Vec::with_capacity(
                current.prefix().len() + generated.generated_block().len() + current.suffix().len(),
            );
            bytes.extend_from_slice(current.prefix());
            bytes.extend_from_slice(generated.generated_block());
            bytes.extend_from_slice(current.suffix());
            let disposition = if bytes == existing {
                WriteDisposition::Unchanged
            } else {
                WriteDisposition::ReplaceFencedBlock
            };
            Ok(PlannedWrite { bytes, disposition })
        }
        None if force => Ok(PlannedWrite {
            bytes: generated_document.to_vec(),
            disposition: WriteDisposition::ForceRewriteUnfenced,
        }),
        None => Err(FenceError::ExistingUnfencedAgentsMd),
    }
}

// The write planner's dispositions (create / force-rewrite / replace-block /
// unchanged, plus non-UTF-8 preservation) and the two fence-policy errors are
// exercised through the public `plan_agents_write` in
// `crates/workflow/tests/agents_fences_render.rs`.
