//! Build-time codegen for embedded prompt corpora.
//!
//! A crate's `build.rs` calls [`emit`]; every markdown document under the
//! tree is embedded and link-checked (a dangling relative link fails the build).

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// [`emit_from`] for a crate's `build.rs`: the tree root is
/// `<CARGO_MANIFEST_DIR>/<tree>/` and the output is `OUT_DIR`.
///
/// # Panics
///
/// Panics on any failure — the caller is a build script and must not
/// limp on.
#[expect(
    clippy::disallowed_methods,
    reason = "build-script crate; cargo communicates CARGO_MANIFEST_DIR and OUT_DIR through the env"
)]
pub fn emit(tree: &str) {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    if let Err(err) = emit_from(&manifest_dir.join(tree), &out_dir) {
        panic!("prose codegen failed for {}: {err}", manifest_dir.join(tree).display());
    }
}

/// Walk `root` and write the sorted `DOCS` table to
/// `<out_dir>/prose_docs.rs`, printing `cargo:rerun-if-changed` for
/// every directory and document walked.
///
/// The embed set is discovered from disk, not declared by the caller:
/// every markdown document under `root` is embedded, keyed by its
/// root-relative path, after its relative markdown links resolve.
///
/// # Errors
///
/// Returns a rendered message when the tree is missing or holds no
/// markdown documents, when it cannot be walked, when a document
/// carries a dangling relative markdown reference, or when the
/// generated file cannot be written — the caller (a `build.rs`) should
/// fail the build with it.
pub fn emit_from(root: &Path, out_dir: &Path) -> Result<(), String> {
    let mut docs: Vec<(String, PathBuf)> = Vec::new();
    if root.is_dir() {
        walk(root, "", &mut docs)?;
    }
    docs.sort_by(|a, b| a.0.cmp(&b.0));
    if docs.is_empty() {
        return Err(format!("no markdown documents found under {}", root.display()));
    }

    for (_, path) in &docs {
        let body =
            fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
        check_links(path, &body)?;
    }

    let mut out = String::from(
        "// @generated by prose — do not edit\n\
         \n\
         /// Every embedded prompt document, sorted by tree-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );
    for (rel, resolved) in &docs {
        writeln!(
            out,
            "    Doc {{ path: {rel:?}, body: include_str!({resolved:?}) }},",
            resolved = resolved.display().to_string(),
        )
        .map_err(|err| err.to_string())?;
    }
    out.push_str("];\n");

    fs::write(out_dir.join("prose_docs.rs"), out).map_err(|err| err.to_string())
}

// Collect every `.md` file under `dir` as `(tree-relative path,
// resolved absolute path)`, descending through directory symlinks.
fn walk(dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let entries = fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("walk {}: {err}", dir.display()))?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let child_rel = if rel.is_empty() { name } else { format!("{rel}/{name}") };
        // `metadata` follows symlinks; a dangling link errors here,
        // failing the build as the embed contract requires.
        let metadata = fs::metadata(&path)
            .map_err(|err| format!("resolve {} (dangling symlink?): {err}", path.display()))?;
        if metadata.is_dir() {
            walk(&path, &child_rel, docs)?;
        } else if metadata.is_file() && path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let resolved = fs::canonicalize(&path)
                .map_err(|err| format!("canonicalize {}: {err}", path.display()))?;
            docs.push((child_rel, resolved));
        }
    }
    Ok(())
}

// Fail when a relative markdown link in `body` does not resolve on
// disk; URLs and same-document anchors are out of scope. Fenced code
// is ignored so casts like Swift `[UInt8](data)` are not links.
fn check_links(source: &Path, body: &str) -> Result<(), String> {
    let dir = source.parent().ok_or_else(|| format!("{} has no parent", source.display()))?;
    let prose = strip_fenced_code(body);
    for target in link_targets(&prose) {
        let path = target.split('#').next().unwrap_or_default();
        if path.is_empty() || target.contains("://") || target.starts_with("mailto:") {
            continue;
        }
        let resolved = dir.join(path);
        if !resolved.exists() {
            return Err(format!(
                "dangling reference in {}: `{target}` does not resolve (checked {})",
                source.display(),
                resolved.display()
            ));
        }
    }
    Ok(())
}

// Drop fenced code blocks (` ``` ` … ` ``` `) so link extraction only
// sees prose. Fence marker lines themselves are discarded.
fn strip_fenced_code(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut in_fence = false;
    for line in body.lines() {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
            continue;
        }
        if !in_fence {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

// Every inline markdown link destination (`](…)`) in `body`, in order.
fn link_targets(body: &str) -> Vec<&str> {
    let mut targets = Vec::new();
    let mut rest = body;
    while let Some(open) = rest.find("](") {
        rest = &rest[open + 2..];
        let Some(close) = rest.find(')') else {
            break;
        };
        targets.push(rest[..close].trim());
        rest = &rest[close + 1..];
    }
    targets
}
