//! Build-time embedding and link checks for prompt corpora.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Run [`emit_from`] using Cargo's manifest and output directories.
///
/// # Panics
///
/// Panics on any failure so the build stops.
pub fn emit(tree: &str) {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    if let Err(err) = emit_from(&manifest_dir.join(tree), &out_dir) {
        panic!("prose codegen failed for {}: {err}", manifest_dir.join(tree).display());
    }
}

/// Write a sorted `DOCS` table to `<out_dir>/prose_docs.rs`.
///
/// Embeds every discovered Markdown file after relative links resolve.
///
/// # Errors
///
/// Returns an error for discovery, link, or output failures.
pub fn emit_from(root: &Path, out_dir: &Path) -> Result<(), String> {
    let mut docs: Vec<(String, PathBuf)> = Vec::new();
    if root.is_dir() {
        walk(root, "", &mut docs, &mut Vec::new())?;
    }
    docs.sort_by(|a, b| a.0.cmp(&b.0));
    if docs.is_empty() {
        return Err(format!("no markdown documents found under {}", root.display()));
    }

    for (_, path) in &docs {
        let body =
            fs::read_to_string(path).map_err(|err| format!("read {}: {err}", path.display()))?;
        check_links(path, &body)?;
    }

    let mut out = String::from(
        "// @generated by prose — do not edit\n\
         \n\
         /// Every embedded prompt document, sorted by tree-relative path.\n\
         pub static DOCS: &[Doc] = &[\n",
    );
    for (rel, resolved) in &docs {
        writeln!(
            out,
            "    Doc {{ path: {rel:?}, body: include_str!({resolved:?}) }},",
            resolved = resolved.display().to_string(),
        )
        .map_err(|err| err.to_string())?;
    }
    out.push_str("];\n");

    fs::write(out_dir.join("prose_docs.rs"), out).map_err(|err| err.to_string())
}

fn walk(
    dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>, stack: &mut Vec<PathBuf>,
) -> Result<(), String> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let canonical =
        fs::canonicalize(dir).map_err(|err| format!("canonicalize {}: {err}", dir.display()))?;
    if stack.contains(&canonical) {
        return Err(format!("symlink cycle: {} re-enters {}", dir.display(), canonical.display()));
    }
    stack.push(canonical);
    let walked = walk_entries(dir, rel, docs, stack);
    stack.pop();
    walked
}

fn walk_entries(
    dir: &Path, rel: &str, docs: &mut Vec<(String, PathBuf)>, stack: &mut Vec<PathBuf>,
) -> Result<(), String> {
    let entries = fs::read_dir(dir).map_err(|err| format!("read {}: {err}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("walk {}: {err}", dir.display()))?;
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let child_rel = if rel.is_empty() { name } else { format!("{rel}/{name}") };
        // Follow directory symlinks; dangling links fail the build.
        let metadata = fs::metadata(&path)
            .map_err(|err| format!("resolve {} (dangling symlink?): {err}", path.display()))?;
        if metadata.is_dir() {
            walk(&path, &child_rel, docs, stack)?;
        } else if metadata.is_file() && path.extension().is_some_and(|ext| ext == "md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let resolved = fs::canonicalize(&path)
                .map_err(|err| format!("canonicalize {}: {err}", path.display()))?;
            docs.push((child_rel, resolved));
        }
    }
    Ok(())
}

// Relative links must resolve; URLs, anchors, and fenced code are excluded.
fn check_links(source: &Path, body: &str) -> Result<(), String> {
    let dir = source.parent().ok_or_else(|| format!("{} has no parent", source.display()))?;
    let prose = strip_fenced_code(body);
    for target in link_targets(&prose) {
        let path = target.split('#').next().unwrap_or_default();
        if path.is_empty() || target.contains("://") || target.starts_with("mailto:") {
            continue;
        }
        let resolved = dir.join(path);
        if !resolved.exists() {
            return Err(format!(
                "dangling reference in {}: `{target}` does not resolve (checked {})",
                source.display(),
                resolved.display()
            ));
        }
    }
    Ok(())
}

// Ignore fenced code so syntax such as Swift `[UInt8](data)` is not a link.
fn strip_fenced_code(body: &str) -> String {
    let mut out = String::with_capacity(body.len());
    let mut in_fence = false;
    for line in body.lines() {
        if line.trim_start().starts_with("```") {
            in_fence = !in_fence;
            continue;
        }
        if !in_fence {
            out.push_str(line);
            out.push('\n');
        }
    }
    out
}

fn link_targets(body: &str) -> Vec<&str> {
    let mut targets = Vec::new();
    let mut rest = body;
    while let Some(open) = rest.find("](") {
        rest = &rest[open + 2..];
        let Some(close) = rest.find(')') else {
            break;
        };
        targets.push(rest[..close].trim());
        rest = &rest[close + 1..];
    }
    targets
}
