// Contracts-build phase driver (RM-01 plan, C13).
//
// Plugs into the same `PhaseDriver` interface the C12 stub / agent
// drivers use, but for the projectless contract slice ALSO emits a
// realistic-but-deterministic OpenAPI 3.1 + JSON Schema bundle into
// the hub's baseline `contracts/` tree. Implementation slices keep
// the deterministic stub driver via the C13 `phaseDriverFor` per-
// slice dispatch on `ScriptedExecuteBackend` /
// `ScriptedFinalizeBackend`.
//
// Why "deterministic but real":
//   * the YAML must pass the contracts WASI tool's checks (RFC-12
//     §Validation rules: SemVer `info.version`, kebab-case
//     `info.x-specify-id`, no broken `$ref`s, etc.) — so the
//     `contract-slice-yaml-validates-via-tool` assertion can
//     actually run the validator and assert `ok: true`,
//   * the bodies stay byte-for-byte stable so a CI re-run never
//     produces a diff,
//   * each file carries a `# STUB:` header marking it as a
//     deterministic test fixture (not real `/spec:build` output) —
//     mirroring the C12 stub `STUB:`-marker convention.
//
// The driver writes contract YAMLs directly into `<hubDir>/contracts/
// {http,schemas}/`. The contract slice is projectless in the loop
// driver, so for the contract slice the `driveSliceWithBodies`
// helper writes only `.specify/specs/<slice>/` + `.specify/archive/
// <slice>/` (no git involvement). Adding `<hubDir>/contracts/*.yaml`
// is a pure file-write that the C13 assertion handlers then probe.

import { ensureDir } from "jsr:@std/fs@1";
import { dirname, join } from "jsr:@std/path@1";

import {
  driveSliceWithBodies,
  stubBodyFactory,
} from "./phase-driver.ts";
import type {
  DriveSliceOpts,
  DriveSliceResult,
  PhaseDriver,
} from "./phase-driver.ts";

/**
 * Contract YAML files the driver emits for the RM-01 OAuth-login
 * fixture. Paths are relative to `<hubDir>/contracts/`. Every body
 * has been validated by `specify tool run contract` against the
 * locally-built `contract-0.2.0.wasm` from
 * `specify-cli/crates/contract-validate/dist/`.
 *
 * The list is exported so the
 * `contract-slice-includes-required-schemas` assertion handler can
 * check against the same canonical names without re-deriving them.
 */
export const CONTRACT_YAML_PATHS = [
  "http/oauth-login.yaml",
  "schemas/oauth-token-request.yaml",
  "schemas/oauth-token-response.yaml",
  "schemas/error-response.yaml",
] as const;

export type ContractYamlPath = typeof CONTRACT_YAML_PATHS[number];

/**
 * Body bundle the driver writes for the RM-01 contract slice. Each
 * value is the literal YAML string written to disk. Marked `STUB:`
 * in a leading comment so a reader can tell it is a deterministic
 * fixture rather than real `/spec:build` output, but the YAML
 * itself is valid OpenAPI 3.1 / JSON Schema 2020-12 and passes the
 * contracts WASI tool unchanged.
 */
const CONTRACT_BODIES: Record<ContractYamlPath, string> = {
  "http/oauth-login.yaml": `# STUB: deterministic OpenAPI 3.1 fixture for the RM-01 contract slice.
# Generated by the C13 ContractsBuildPhaseDriver. Validates via
# \`specify tool run contract\`. Replace with real \`/spec:build\` output
# for production runs.
openapi: "3.1.0"
info:
  title: OAuth Login API
  version: "1.0.0"
  description: |
    HTTP API for starting, exchanging, and refreshing third-party OAuth login
    sessions for the RM-01 fixture. Provider name is parameterised on the
    path so adding a third provider is a contract-only change.
  x-specify-id: oauth-login
paths:
  /oauth/{provider}/start:
    post:
      summary: Start a third-party OAuth flow.
      operationId: startOauthLogin
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [google, apple]
            description: OAuth identity provider name.
      responses:
        "200":
          description: Provider authorization URL the client should redirect to.
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorization_url:
                    type: string
                    format: uri
                    description: URL the client should send the user to.
                  state:
                    type: string
                    description: Opaque state value the client must echo back.
                required:
                  - authorization_url
                  - state
                additionalProperties: false
        "400":
          description: Invalid provider or request shape.
          content:
            application/json:
              schema:
                $ref: "../schemas/error-response.yaml"
  /oauth/token:
    post:
      summary: Exchange a provider authorization code for a Shop session.
      operationId: exchangeOauthToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/oauth-token-request.yaml"
      responses:
        "200":
          description: Shop session tokens issued.
          content:
            application/json:
              schema:
                $ref: "../schemas/oauth-token-response.yaml"
        "400":
          description: Provider rejected the code or the request was malformed.
          content:
            application/json:
              schema:
                $ref: "../schemas/error-response.yaml"
  /oauth/refresh:
    post:
      summary: Refresh a Shop access token.
      operationId: refreshOauthToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  minLength: 1
                  description: Long-lived Shop refresh token from a prior exchange.
              required:
                - refresh_token
              additionalProperties: false
      responses:
        "200":
          description: New Shop session tokens.
          content:
            application/json:
              schema:
                $ref: "../schemas/oauth-token-response.yaml"
        "401":
          description: Refresh token expired or invalid; client must re-authenticate.
          content:
            application/json:
              schema:
                $ref: "../schemas/error-response.yaml"
`,

  "schemas/oauth-token-request.yaml": `# STUB: deterministic JSON Schema fixture (C13 ContractsBuildPhaseDriver).
$id: "urn:specify:schemas/oauth-token-request"
$schema: "https://json-schema.org/draft/2020-12/schema"
title: OauthTokenRequest
description: Payload exchanging a provider authorization code for a Shop session.
type: object
properties:
  provider:
    type: string
    enum: [google, apple]
    description: OAuth identity provider the code was issued by.
  code:
    type: string
    minLength: 1
    description: Authorization code returned by the provider.
  redirect_uri:
    type: string
    format: uri
    description: Redirect URI the provider used; echoed for verification.
required:
  - provider
  - code
  - redirect_uri
additionalProperties: false
`,

  "schemas/oauth-token-response.yaml": `# STUB: deterministic JSON Schema fixture (C13 ContractsBuildPhaseDriver).
$id: "urn:specify:schemas/oauth-token-response"
$schema: "https://json-schema.org/draft/2020-12/schema"
title: OauthTokenResponse
description: Shop-issued session tokens returned after a successful exchange or refresh.
type: object
properties:
  access_token:
    type: string
    minLength: 1
    description: Short-lived Shop access token.
  refresh_token:
    type: string
    minLength: 1
    description: Long-lived Shop refresh token. Mobile clients store this securely.
  expires_in:
    type: integer
    minimum: 1
    description: Lifetime in seconds of the access token.
  token_type:
    type: string
    enum: [Bearer]
    description: Token type. Always Bearer.
required:
  - access_token
  - refresh_token
  - expires_in
  - token_type
additionalProperties: false
`,

  "schemas/error-response.yaml": `# STUB: deterministic JSON Schema fixture (C13 ContractsBuildPhaseDriver).
$id: "urn:specify:schemas/error-response"
$schema: "https://json-schema.org/draft/2020-12/schema"
title: ErrorResponse
description: Structured error returned by the OAuth login endpoints.
type: object
properties:
  error:
    type: string
    enum:
      - user-cancelled
      - provider-rejected
      - session-expired
      - invalid-request
    description: Stable error code apps render distinct UI for.
  message:
    type: string
    description: Human-readable error detail.
required:
  - error
  - message
additionalProperties: false
`,
};

/**
 * Contracts-build phase driver. For the contract slice (projectless,
 * capability=contracts) it runs the standard define+merge lifecycle
 * via `driveSliceWithBodies` AND writes the OpenAPI/JSON-Schema
 * bundle into `<hubDir>/contracts/`. For non-contract slices the
 * driver still works (delegates to the stub bodies) — though the
 * C13 backend uses `phaseDriverFor` so this driver only ever runs
 * for the contract slice in practice. Keeping the fall-through path
 * defensive means a misconfigured backend still produces a sensible
 * action log instead of crashing.
 */
export class ContractsBuildPhaseDriver implements PhaseDriver {
  readonly name = "contracts-build" as const;

  async driveSlice(opts: DriveSliceOpts): Promise<DriveSliceResult> {
    const result = await driveSliceWithBodies(opts, stubBodyFactory);

    const isContractSlice = opts.project === null &&
      opts.capabilityName === "contracts";
    if (!isContractSlice) {
      return result;
    }

    const written = await writeContractBundle(opts.hubDir);
    result.actions.push({
      ts: new Date().toISOString(),
      phase: "build",
      slice: opts.sliceName,
      action: "contracts-build-emit-yaml",
      artifacts: written.map((p) => `contracts/${p}`),
    });
    return result;
  }
}

/**
 * Write every `CONTRACT_YAML_PATHS` entry under `<hubDir>/contracts/`.
 * Returns the relative paths actually written (always the full set
 * for now; the helper is structured so a future amendment can vary
 * by capability brief without changing the call site).
 */
async function writeContractBundle(hubDir: string): Promise<string[]> {
  const written: string[] = [];
  for (const rel of CONTRACT_YAML_PATHS) {
    const abs = join(hubDir, "contracts", rel);
    await ensureDir(dirname(abs));
    await Deno.writeTextFile(abs, CONTRACT_BODIES[rel]);
    written.push(rel);
  }
  return written;
}
