[book]
title = "Specify Developer Guide"
authors = ["Augentic"]
language = "en"
src = "."

[output.html]
git-repository-url = "https://github.com/augentic/specify"
additional-css = ["assets/theme/specify-docs.css"]
additional-js = ["assets/theme/authority-widget.js"]

[preprocessor.d2]
layout = "elk"
inline = true

[output.html.fold]
enable = true
level = 1
