// Evidence writers: summary.md, scenario.md, assertions.json, final-tree.txt,
// stdout.log, stderr.log. Optional transcript.md / tool-calls.jsonl filenames
// are reserved on `RunPaths` for later backends; this skeleton does not
// emit them.

import { walk } from "jsr:@std/fs@1/walk";
import { relative } from "jsr:@std/path@1";

import type {
  AssertionRecord,
  BackendResult,
  RunContext,
  RunPaths,
  Scenario,
} from "./types.ts";

const FINAL_TREE_SKIP = [/\/\.git(\/|$)/, /\/node_modules(\/|$)/];

/** Copy the executed scenario verbatim so the run is self-describing. */
export async function writeScenarioCopy(
  paths: RunPaths,
  scenario: Scenario,
): Promise<void> {
  await Deno.copyFile(scenario.filePath, paths.scenarioMd);
}

/** Initialise empty stdout/stderr/assertions sinks before the backend runs. */
export async function initEmptyEvidence(paths: RunPaths): Promise<void> {
  await Deno.writeTextFile(paths.stdoutLog, "");
  await Deno.writeTextFile(paths.stderrLog, "");
  await Deno.writeTextFile(
    paths.assertionsJson,
    JSON.stringify({ assertions: [] }, null, 2) + "\n",
  );
}

/** Append text to a log path. Backends and the runner share these helpers. */
export async function appendLog(path: string, text: string): Promise<void> {
  await Deno.writeTextFile(path, text, { append: true });
}

/** Write the structured assertion list. */
export async function writeAssertions(
  paths: RunPaths,
  assertions: AssertionRecord[],
): Promise<void> {
  const payload = { assertions };
  await Deno.writeTextFile(
    paths.assertionsJson,
    JSON.stringify(payload, null, 2) + "\n",
  );
}

/**
 * Recursive listing of the workspace tree at end of run, with byte sizes.
 * Skips noisy directories (`.git`, `node_modules`) so the listing stays
 * useful for human inspection.
 */
export async function writeFinalTree(paths: RunPaths): Promise<void> {
  const lines: string[] = [];
  try {
    for await (const entry of walk(paths.workspace, {
      includeDirs: true,
      followSymlinks: false,
    })) {
      if (FINAL_TREE_SKIP.some((re) => re.test(entry.path))) continue;
      const rel = relative(paths.workspace, entry.path) || ".";
      let line = rel;
      if (entry.isFile) {
        try {
          const stat = await Deno.stat(entry.path);
          line += `\t${stat.size}`;
        } catch {
          line += "\t?";
        }
      } else if (entry.isDirectory) {
        line += "/";
      } else if (entry.isSymlink) {
        line += "\t(symlink)";
      }
      lines.push(line);
    }
  } catch (e) {
    if (!(e instanceof Deno.errors.NotFound)) throw e;
  }
  lines.sort();
  await Deno.writeTextFile(paths.finalTreeTxt, lines.join("\n") + "\n");
}

/**
 * Render the human-readable run summary. Mirrors the shape the contracts
 * `run-summary-template.md` expects so a human-driven run today produces
 * output the runner can replicate mechanically tomorrow.
 */
export async function writeSummary(
  ctx: RunContext,
  result: BackendResult,
  finishedAt: string,
): Promise<void> {
  const { scenario, paths } = ctx;
  const fm = scenario.frontmatter;

  const verdictLine = result.verdict === "pending-operator"
    ? "**Result:** `pending-operator` (manual backend recorded the run; no automated assertion yet)"
    : `**Result:** \`${result.verdict}\``;

  const faultLine = result.faultDomain
    ? `\n- **Fault domain:** \`${result.faultDomain}\``
    : "";

  const assertionsTable = result.assertions.length === 0
    ? "_No assertion records emitted by this backend._"
    : [
      "| Assertion id | Verdict | Fault domain | Evidence |",
      "| --- | --- | --- | --- |",
      ...result.assertions.map((a) =>
        `| \`${a.id}\` | \`${a.verdict}\` | ${a["fault-domain"] ? `\`${a["fault-domain"]}\`` : "—"} | ${escapeCell(a.evidence)} |`
      ),
    ].join("\n");

  const stubbed = result.evidence?.extras?.stubbed as
    | {
      scenario: string;
      slice: string;
      stubbedStages: ReadonlyArray<string>;
      skipped?: boolean;
      reason?: string | null;
      actions: Array<{
        phase: string;
        action: string;
        artifacts: string[];
        command?: string[];
      }>;
    }
    | undefined;
  const stubbedSection = stubbed
    ? renderStubbedSection(stubbed)
    : null;

  const lines = [
    `# Scenario Run Summary: ${fm.id}`,
    "",
    `> Generated by \`acceptance/runner/main.ts\`. Mirrors the shape in`,
    `> [\`run-summary-template.md\`](../../../capabilities/contracts/tests/run-summary-template.md)`,
    `> so manual and automated runs produce comparable evidence.`,
    "",
    "## Run Header",
    "",
    `- **Scenario ID:** \`${fm.id}\``,
    `- **Scenario file:** \`${scenario.relPath}\``,
    `- **Capability:** ${fm.capability ? `\`${fm.capability}\`` : "_n/a_"}`,
    `- **Backend:** \`${fm.backend}\``,
    `- **Entrypoint:** \`${fm.entrypoint}\``,
    `- **Stages:** ${fm.stages.map((s) => `\`${s}\``).join(", ")}`,
    `- **Isolation:** \`${fm.isolation}\``,
    `- **Run id:** \`${runIdFromPath(paths.runDir)}\``,
    `- **Started at:** \`${ctx.startedAt}\``,
    `- **Finished at:** \`${finishedAt}\``,
    `- **Workspace root:** \`${paths.workspace}\``,
    `- **Run directory:** \`${paths.runDir}\``,
    "",
    "## Verdict",
    "",
    `- ${verdictLine}${faultLine}`,
    `- **Notes:** ${result.notes ? result.notes : "—"}`,
    "",
    "## Assertions",
    "",
    assertionsTable,
    "",
  ];
  if (stubbedSection) {
    lines.push(...stubbedSection, "");
  }
  lines.push(
    "## Evidence Files",
    "",
    "- `scenario.md` — copy of the executed scenario.",
    "- `assertions.json` — structured assertion records.",
    "- `final-tree.txt` — recursive listing of the workspace at end of run.",
    "- `stdout.log`, `stderr.log` — captured streams (may be empty for the manual backend).",
    `- ${stubbed ? "`stub-actions.jsonl` — per-CLI-action log written by the stub backend (C08)." : "`stub-actions.jsonl` — written when the stub backend (C08) drove the run; not present for this run."}`,
    "- `transcript.md` / `tool-calls.jsonl` — reserved for agent and recorded backends; not written by this run.",
    "",
  );
  await Deno.writeTextFile(paths.summaryMd, lines.join("\n"));
}

function renderStubbedSection(
  stubbed: {
    scenario: string;
    slice: string;
    stubbedStages: ReadonlyArray<string>;
    skipped?: boolean;
    reason?: string | null;
    actions: Array<{
      phase: string;
      action: string;
      artifacts: string[];
      command?: string[];
    }>;
  },
): string[] {
  const head = [
    "## Stub Backend Disclosure",
    "",
    `> **Stub backend was used.** Lifecycle phases listed below were ` +
      `driven through the \`specify\` CLI by the deterministic stub, ` +
      `not a live agent. Real-world behaviour may differ.`,
    "",
    `- **Slice:** \`${stubbed.slice}\``,
    `- **Stubbed stages:** ${
      stubbed.stubbedStages.length
        ? stubbed.stubbedStages.map((s) => `\`${s}\``).join(", ")
        : "_none_"
    }`,
    `- **Action count:** ${stubbed.actions.length}`,
  ];
  if (stubbed.skipped) {
    head.push(
      `- **Skipped:** \`${stubbed.reason ?? "(no reason recorded)"}\``,
    );
  }
  if (stubbed.actions.length === 0) return head;
  head.push(
    "",
    "| Phase | Action | Command | Artifacts |",
    "| --- | --- | --- | --- |",
  );
  for (const a of stubbed.actions) {
    head.push(
      `| \`${a.phase}\` | \`${a.action}\` | ${
        a.command ? `\`specify ${a.command.join(" ")}\`` : "—"
      } | ${
        a.artifacts.length === 0 ? "—" : a.artifacts.map((p) => `\`${p}\``).join(", ")
      } |`,
    );
  }
  return head;
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").trim() || "—";
}

function runIdFromPath(runDir: string): string {
  const parts = runDir.split("/");
  return parts[parts.length - 1] ?? runDir;
}
