name: Docs

on:
  push:
    # branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yaml"
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: jontze/action-mdbook@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-mermaid: true

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages project list
            pages deploy docs/book --project-name=specify-docs
